import type { Metadata } from "next";

import "./globals.css";
import { manropeLocal } from "@/components/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeLocal.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
